import { defineCollection, defineConfig, s } from "velite";

const region = s.enum(["africa", "asia", "europe", "n-america", "s-america"]);
const wpSlug = s.enum(["wp1", "wp2", "wp3", "wp4", "wp5"]);
const assetRef = s.object({
  src: s.string(),
  alt_en: s.string().min(1),
  alt_fr: s.string().optional(),
  credit: s.string().optional(),
  license: s.string().optional(),
  width: s.number().optional(),
  height: s.number().optional(),
});

const people = defineCollection({
  name: "Person",
  pattern: "people/**/*.mdx",
  schema: s.object({
    slug: s.slug(),
    fullName: s.string(),
    shortName: s.string().optional(),
    title: s.string(),
    honorific: s.string().optional(),
    affiliations: s.array(s.string()),
    primaryAffiliation: s.string(),
    workPackages: s.array(wpSlug),
    role: s.enum(["pi", "wp-lead", "core-team", "partner-lead", "team-member"]),
    bio_en: s.string(),
    bio_fr: s.string().optional(),
    bio_es: s.string().optional(),
    expertise: s.array(s.string()).optional(),
    email: s.string().email().optional(),
    orcid: s.string().optional(),
    portrait: assetRef.optional(),
    links: s.array(s.object({ label: s.string(), url: s.string().url() })).optional(),
    isPublic: s.boolean(),
    lastUpdated: s.isodate(),
    content: s.mdx(),
  }),
});

const institutes = defineCollection({
  name: "Institute",
  pattern: "institutes/**/*.mdx",
  schema: s.object({
    slug: s.slug(),
    name: s.string(),
    shortName: s.string().optional(),
    city: s.string(),
    country: s.string(),
    countryCode: s.string().length(2),
    region,
    coordinates: s.tuple([s.number(), s.number()]),
    url: s.string().url().optional(),
    logo: assetRef.optional(),
    description_en: s.string().optional(),
    description_fr: s.string().optional(),
    description_es: s.string().optional(),
    leadInvestigators: s.array(s.string()),
    workPackages: s.array(wpSlug),
    isCoreInstitution: s.boolean(),
    joinedDate: s.isodate().optional(),
    lastUpdated: s.isodate(),
    content: s.mdx(),
  }),
});

const workPackages = defineCollection({
  name: "WorkPackage",
  pattern: "work-packages/**/*.mdx",
  schema: s.object({
    slug: wpSlug,
    number: s.union([s.literal(1), s.literal(2), s.literal(3), s.literal(4), s.literal(5)]),
    title_en: s.string(),
    title_fr: s.string().optional(),
    title_es: s.string().optional(),
    shortTitle_en: s.string(),
    hook_en: s.string().max(120),
    summary_en: s.string(),
    body_en: s.string().optional(),
    hook_fr: s.string().optional(),
    summary_fr: s.string().optional(),
    body_fr: s.string().optional(),
    leadPI: s.string(),
    coreTeam: s.array(s.string()),
    diagram: assetRef.optional(),
    position: s.union([s.literal(1), s.literal(2), s.literal(3), s.literal(4), s.literal(5)]),
    isCentral: s.boolean(),
    status: s.enum(["active", "planned", "completed"]),
    lastUpdated: s.isodate(),
    content: s.mdx(),
  }),
});

const meetings = defineCollection({
  name: "Meeting",
  pattern: "meetings/**/*.mdx",
  schema: s.object({
    slug: s.slug(),
    title: s.string(),
    date: s.isodate(),
    endDate: s.isodate().optional(),
    location: s.string().optional(),
    isVirtual: s.boolean().optional(),
    description_en: s.string().optional(),
    description_fr: s.string().optional(),
    attendees: s.array(s.string()).optional(),
    workPackages: s.array(wpSlug).optional(),
    status: s.enum(["upcoming", "past"]),
    publicSummary_en: s.string().optional(),
    lastUpdated: s.isodate(),
    content: s.mdx(),
  }),
});

const publications = defineCollection({
  name: "Publication",
  pattern: "publications/**/*.mdx",
  schema: s.object({
    slug: s.slug(),
    title: s.string(),
    authors: s.array(s.string()),
    authorPersons: s.array(s.string()).optional(),
    journal: s.string(),
    year: s.number(),
    doi: s.string().optional(),
    url: s.string().url(),
    abstract_en: s.string().optional(),
    workPackages: s.array(wpSlug),
    isFromECCE: s.boolean(),
    isOpenAccess: s.boolean().optional(),
    publishedDate: s.isodate(),
    lastUpdated: s.isodate(),
    content: s.mdx(),
  }),
});

const insights = defineCollection({
  name: "Insight",
  pattern: "insights/**/*.mdx",
  schema: s.object({
    slug: s.slug(),
    category: s.enum(["field-work", "sample-journey", "pathology", "story", "explainer"]),
    title_en: s.string(),
    title_fr: s.string().optional(),
    hook_en: s.string(),
    body_en: s.string(),
    body_fr: s.string().optional(),
    authorPersons: s.array(s.string()),
    contributingInstitutes: s.array(s.string()).optional(),
    workPackages: s.array(wpSlug).optional(),
    region: region.optional(),
    coverImage: assetRef,
    publishedDate: s.isodate(),
    lastUpdated: s.isodate(),
    isPublic: s.boolean(),
    content: s.mdx(),
  }),
});

const news = defineCollection({
  name: "NewsItem",
  pattern: "news/**/*.mdx",
  schema: s.object({
    slug: s.slug(),
    type: s.enum(["publication", "meeting", "field-report", "press", "milestone", "announcement"]),
    title_en: s.string(),
    title_fr: s.string().optional(),
    summary_en: s.string().max(280),
    summary_fr: s.string().optional(),
    body_en: s.string().optional(),
    publishedDate: s.isodate(),
    workPackages: s.array(wpSlug).optional(),
    region: region.optional(),
    relatedPublication: s.string().optional(),
    relatedMeeting: s.string().optional(),
    relatedPersons: s.array(s.string()).optional(),
    coverImage: assetRef.optional(),
    externalUrl: s.string().url().optional(),
    isPublic: s.boolean(),
    lastUpdated: s.isodate(),
    content: s.mdx(),
  }),
});

export default defineConfig({
  root: "content",
  strict: true,
  output: {
    data: ".velite",
    assets: "public/static",
    base: "/static/",
    name: "[name]-[hash:8].[ext]",
    clean: false,
    format: "esm",
  },
  collections: {
    people,
    institutes,
    workPackages,
    meetings,
    publications,
    insights,
    news,
  },
});
