import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

type TokenLeaf = {
  value: unknown;
  comment?: string;
};

interface TokenTree {
  [key: string]: TokenLeaf | TokenTree;
}

const tokenPath = join(process.cwd(), "src", "lib", "design", "design-tokens.json");
const outputPath = join(process.cwd(), "src", "styles", "tokens.css");
const tokens = JSON.parse(readFileSync(tokenPath, "utf8")) as TokenTree;

const isLeaf = (value: TokenLeaf | TokenTree): value is TokenLeaf =>
  typeof value === "object" && value !== null && "value" in value;

const toName = (parts: string[]): string =>
  `--ecce-${parts
    .map((part) => part.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase())
    .join("-")}`;

const renderValue = (value: unknown): string => {
  if (Array.isArray(value)) return value.join(", ");
  if (typeof value === "boolean") return value ? "1" : "0";
  return String(value);
};

const walk = (tree: TokenTree, parts: string[] = []): string[] =>
  Object.entries(tree).flatMap(([key, value]) => {
    if (key.startsWith("$") || key === "metadata" || key === "comment") return [];
    if (typeof value !== "object" || value === null) return [];
    if (isLeaf(value)) return [`  ${toName([...parts, key])}: ${renderValue(value.value)};`];
    return walk(value, [...parts, key]);
  });

const lines = [
  "/* Generated by scripts/generate-tokens.ts. Do not edit by hand. */",
  ":root {",
  ...walk(tokens),
  "}",
  "",
];

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, lines.join("\n"));
